train: C:/Users/bubbl/Desktop/Contest/AI GO/Classification/datasets/datasets/train
val: C:/Users/bubbl/Desktop/Contest/AI GO/Classification/datasets/datasets/valid
test: C:/Users/bubbl/Desktop/Contest/AI GO/GAN_Test/Dataset/Test/jpg

nc: 8
names: [other,'obj1', 'obj2', 'obj3', 'obj4', 'obj5', 'obj6', 'obj7']

